---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template to create 3 private and 3 public subnets. Each public subnet will have NAT Gateway that provides internet access for private subnets.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPC
      - AvailabilityZone1
      - AvailabilityZone2
      - AvailabilityZone3
      - PublicSubnet1Cidr
      - PublicSubnet2Cidr
      - PublicSubnet3Cidr
      - PrivateSubnet1Cidr
      - PrivateSubnet2Cidr
      - PrivateSubnet3Cidr
      - PublicSubnetRouteTableId
Parameters:
  VPC:
    Description: This is the VPC the stack will be deployed inside.
    Type: AWS::EC2::VPC::Id
    Default: vpc-5674e132
  AvailabilityZone1:
    Description: Availability zone 1
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-west-1a
  AvailabilityZone2:
    Description: Availability zone 2
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-west-1b
  AvailabilityZone3:
    Description: Availability zone 3
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-west-1c
  PublicSubnet1Cidr:
    Description: CIDR for Public subnet 1
    Type: String
    Default: 172.24.250.0/28
  PublicSubnet2Cidr:
    Description: CIDR for Public subnet 2
    Type: String
    Default: 172.24.250.16/28
  PublicSubnet3Cidr:
    Description: CIDR for Public subnet 3
    Type: String
    Default: 172.24.250.32/28
  PrivateSubnet1Cidr:
    Description: CIDR for Private subnet 1
    Type: String
    Default: 172.24.251.0/24
  PrivateSubnet2Cidr:
    Description: CIDR for Private subnet 2
    Type: String
    Default: 172.24.252.0/24
  PrivateSubnet3Cidr:
    Description: CIDR for Private subnet 3
    Type: String
    Default: 172.24.253.0/24
  PublicSubnetRouteTableId:
    Description: RouteTableId for public subnets
    Type: String
    Default: rtb-4f85d32b
Resources:
  # Public subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PublicSubnet1Cidr
      AvailabilityZone:
        Ref: AvailabilityZone1
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PublicSubnet2Cidr
      AvailabilityZone:
        Ref: AvailabilityZone2
  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PublicSubnet3Cidr
      AvailabilityZone:
        Ref: AvailabilityZone3
  # Private subnets
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PrivateSubnet1Cidr
      AvailabilityZone:
        Ref: AvailabilityZone1
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PrivateSubnet2Cidr
      AvailabilityZone:
        Ref: AvailabilityZone2
  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PrivateSubnet3Cidr
      AvailabilityZone:
        Ref: AvailabilityZone3
  # Public subnet route table association
  PublicSubnet1Route:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTableId
      SubnetId:
        Ref: PublicSubnet1
  PublicSubnet2Route:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTableId
      SubnetId:
        Ref: PublicSubnet2
  PublicSubnet3Route:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTableId
      SubnetId:
        Ref: PublicSubnet3
  # NAT Gateways with ElasticIPs for Public subnets
  ElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Ref: VPC
  ElasticIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Ref: VPC
  ElasticIP3:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Ref: VPC
  NatGW1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Ref: ElasticIP1
      SubnetId:
        Ref: PublicSubnet1
  NatGW2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Ref: ElasticIP2
      SubnetId:
        Ref: PublicSubnet2
  NatGW3:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Ref: ElasticIP3
      SubnetId:
        Ref: PublicSubnet3
