---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template to spin-up jumpbox in Neo4j HA Public subnet

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPC
      - SubnetId
    - Label:
        default: Amazon EC2 Configuration
      Parameters:
      - InstanceType
      - ImageId
      - IamInstanceProfile
      - InstanceKey

    ParameterLabels:
      AutoGroupAvailabilityZones:
        deafault: Auto Group Availability Zones
      InstanceType:
        default: Instance Type
      InstanceKey:
        default: Instance EC2 User Key

Parameters:
  VPC:
    Description: This is the VPC the stack will be deployed inside.
    Type: AWS::EC2::VPC::Id
    Default: vpc-5674e132
  SubnetId:
    Description: Public subnet, Neo4j HA Public Subnet 1, eu-west-1a
    Type: AWS::EC2::Subnet::Id
    Default: subnet-f293a584
  AvailabilityZone:
    Description: AvailabilityZone to place instance into, eu-west-1a
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-west-1a
  SecurityGroupId:
    Description: sg-21e9bd47 in VPC vpc-9fcb94fb, allow SSH and HTTP(S) inbound
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-dd5813bb
  DeploymentScriptURL:
    Description: Deployment script URL
    Type: String
    Default: https://raw.githubusercontent.com/Financial-Times/up-neo4j-ha-cluster/master/sh/jumpbox.sh
  InstanceKey:
    Description: EC2User Key
    Type: AWS::EC2::KeyPair::KeyName
    Default: jussi.heinonen.universal.publishing
  ImageId:
    Description: Amazon Linux AMI 2016.09.1 (HVM), SSD Volume Type
    Type: String
    Default: ami-c51e3eb6
  IamInstanceProfile:
    Description: What IAM role to give to this instance
    Type: String
    Default: FT-Linux-Role
  TagEnvironment:
    Description: Tag detail for the Environment
    Type: String
    AllowedValues:
      - 'd'
      - 't'
      - 'p'
      - 'int'
    Default: d
  TagTeamDL:
    Description: Tag of the TeamDL.
    Type: String
    ConstraintDescription: There must be a valid email address for the TeamDL
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    Default: universal.publishing.platform@ft.com
  TagSystemCode:
    Description: Tag detail for the SystemCode
    Type: String
    Default: UPP Neo4j HA
  TagIpCode:
    Description: Tag detail for the ipCode
    Type: String
    Default: P196
  TagDescription:
    Description: Instance description
    Type: String
    Default: Neo4j HA Jumpbox
  TagStopSchedule:
    Description: Tag detail for the when the instance is to be powered off.
    Type: String
    Default: '{ "start": "0 9 * * 1-5", "stop": "55 17 * * *" }'
  InstanceType:
    Description: The type and size of the instance. Check documentation for recommended types.
    Type: String
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - p2.xlarge
    - p2.8xlarge
    - p2.16xlarge
    - g2.2xlarge
    - g2.8xlarge
    - x1.32xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    Default: t2.small

Conditions:
  HasKeyName:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: InstanceKey

Resources:
  # Jumpbox security group
  JumpboxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from known subnets and IP addresses
      VpcId: !Ref VPC
      Tags:
      - Key: environment
        Value: !Ref TagEnvironment
      - Key: teamDL
        Value: !Ref TagTeamDL
      - Key: systemCode
        Value: !Ref TagSystemCode
      - Key: Name
        Value: Neo4j HA jumpbox
      - Key: ipCode
        Value:
          Ref: TagIpCode
      SecurityGroupIngress:
      # OSB + LDNWebPerf
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 82.136.1.214/32
      # XP - Cluj Office
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 194.117.242.0/23
      # EU VPN Client
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 62.25.64.1/32
      # US VPN Client
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 64.210.200.1/32
  # Jumpbox instane definition
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
      - Ref: JumpboxSecurityGroup
      SubnetId:
        Ref: SubnetId
      AvailabilityZone:
        Ref: AvailabilityZone
      InstanceType:
        Ref: InstanceType
      ImageId:
        Ref: ImageId
      KeyName:
        Fn::If:
        - HasKeyName
        - Ref: InstanceKey
        - Ref: AWS::NoValue
      IamInstanceProfile:
        Ref: IamInstanceProfile
      Tags:
      - Key: environment
        Value:
          Ref: TagEnvironment
      - Key: teamDL
        Value:
          Ref: TagTeamDL
      - Key: systemCode
        Value:
          Ref: TagSystemCode
      - Key: ipCode
        Value:
          Ref: TagIpCode
      - Key: description
        Value:
          Ref: TagDescription
      - Key: ec2Powercycle
        Value:
          Ref: TagStopSchedule
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Pull and execute deployment script
          /usr/bin/curl -s ${DeploymentScriptURL} | /bin/bash
